DROP DATABASE IF EXISTS avelaDB;
CREATE DATABASE avelaDB;

USE avelaDB;

CREATE TABLE movies (
    id INT(10) AUTO_INCREMENT NOT NULL,
    movie_name LONGTEXT NOT NULL,
    likes INT(255) NOT NULL,
    PRIMARY KEY (id)
);
